<a href="https://colab.research.google.com/github/Ruijia0/SupplyChain_Analytics/blob/main/Exchange_Rate_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt

# === Step 1: Load Historical Exchange Rate Data ===
# Assuming the exchange rates data is already loaded as a DataFrame
# For this notebook, we generate synthetic data as a placeholder
np.random.seed(42)
num_countries = 5  # Example: Exchange rates for 5 countries
num_days = 500

# Generate synthetic exchange rate data
mean_rates = np.array([1.2, 0.8, 1.5, 1.1, 0.9])  # Example mean exchange rates
cov_matrix = np.array([
    [0.01, 0.005, 0.004, 0.003, 0.002],
    [0.005, 0.02, 0.006, 0.004, 0.003],
    [0.004, 0.006, 0.015, 0.005, 0.004],
    [0.003, 0.004, 0.005, 0.01, 0.003],
    [0.002, 0.003, 0.004, 0.003, 0.02]
])
exchange_rates = np.random.multivariate_normal(mean_rates, cov_matrix, size=num_days)

# Convert to DataFrame for analysis
exchange_rates_df = pd.DataFrame(exchange_rates, columns=[f'Country_{i+1}' for i in range(num_countries)])

# === Step 2: Approximate Distribution and Sample ===
# Estimate mean and covariance from historical data
estimated_mean = exchange_rates_df.mean().values
estimated_cov = exchange_rates_df.cov().values

# Sample 100 draws from the estimated multivariate normal distribution
num_samples = 100
samples = np.random.multivariate_normal(estimated_mean, estimated_cov, size=num_samples)

# === Step 3: Optimize Network Configuration for Each Sample ===
def optimize_network(exchange_rates):
    # Placeholder optimization function
    # Returns a random network configuration (0 = closed, 1 = open)
    num_plants = 5  # Example: Assume 5 plants
    return np.random.choice([0, 1], size=num_plants)

# Optimize for all samples
optimal_configurations = np.array([optimize_network(sample) for sample in samples])

# === Step 4: Analyze Results ===
# Calculate the frequency of each plant being open across scenarios
plant_open_frequencies = optimal_configurations.mean(axis=0)

# Identify patterns (pairs of plants that correlate in open/close decisions)
correlation_matrix = np.corrcoef(optimal_configurations, rowvar=False)

# === Step 5: Propose Strategies ===
def propose_strategies(frequencies, correlation_matrix):
    # Strategy 1: Plants with high open frequency are kept open
    threshold = 0.7  # Example threshold
    strategy_1 = (frequencies > threshold).astype(int)

    # Strategy 2: Consider pair correlations (open pairs together)
    correlated_pairs = np.where(correlation_matrix > 0.8)  # Example cutoff for high correlation
    strategy_2 = strategy_1.copy()
    for i, j in zip(*correlated_pairs):
        if i != j:  # Avoid self-correlation
            strategy_2[i] = strategy_2[j]

    # Strategy 3: Plants with low open frequency are kept closed
    threshold_low = 0.3  # Example threshold
    strategy_3 = (frequencies > threshold_low).astype(int)

    return strategy_1, strategy_2, strategy_3

strategy_1, strategy_2, strategy_3 = propose_strategies(plant_open_frequencies, correlation_matrix)

# === Step 6: Evaluate Strategies ===
def evaluate_strategy(strategy, samples):
    # Placeholder cost evaluation function
    # Assume the cost is inversely proportional to the number of open plants
    costs = []
    for sample in samples:
        cost = np.sum(strategy) * np.mean(sample)  # Example cost function
        costs.append(cost)
    return np.mean(costs), np.std(costs)

# Evaluate the three strategies
strategy_costs = {}
for i, strategy in enumerate([strategy_1, strategy_2, strategy_3], start=1):
    mean_cost, std_cost = evaluate_strategy(strategy, samples)
    strategy_costs[f'Strategy_{i}'] = {'mean_cost': mean_cost, 'std_cost': std_cost}

# Determine the recommended strategy
recommended_strategy = min(strategy_costs, key=lambda x: strategy_costs[x]['mean_cost'])

# === Display Results ===
print("Optimal Configurations (Sampled):")
print(optimal_configurations)
print("\nPlant Open Frequencies:", plant_open_frequencies)
print("\nStrategy Costs:", strategy_costs)
print(f"\nRecommended Strategy: {recommended_strategy}")


Optimal Configurations (Sampled):
[[1 1 1 1 0]
 [0 0 1 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [1 0 0 0 0]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 0]
 [1 0 0 0 0]
 [0 0 1 0 1]
 [1 0 1 1 0]
 [0 0 1 1 0]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 1 1 1]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [0 1 1 0 1]
 [1 1 1 0 1]
 [0 0 1 1 1]
 [0 1 1 1 1]
 [1 0 1 1 1]
 [0 1 0 0 1]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [0 1 1 0 0]
 [1 0 0 1 0]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [1 0 1 0 0]
 [0 1 1 1 1]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [0 1 0 0 0]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [1 0 0 0 0]
 [1 0 0 1 1]
 [0 1 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [1 1 0 1 0]
 [1 1 0 1 1]
 [0 0 1 1 1]
 [0 1 1 1 0]
 [0 0 0 1 0]
 [1 1 1 1 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 1 1 1 0]
 [1 1 1 0 0]
 [1 0 0 1 0]
 [0 0 1 1 1]
 [0 1 0 0 0]
 [1 1 1 1 0]
 [1 0 1 1 1]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 1 1 1]
 [0 1 0 0 0]
 [0 0 1 1 0]
 [1 0 1 1 1]
 [1 